"""
Phase 2 - Data profiling for project1_supply_chain_demand.csv.

Deliberately schema-agnostic: the date column and the SKU identifier column are
DETECTED from the data rather than assumed, so the profile is reproducible if the
supplier changes header names.

Writes: backend/reports/data_profile.md
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CSV = ROOT / "data" / "project1_supply_chain_demand.csv"
OUT = ROOT / "backend" / "reports" / "data_profile.md"


# ----------------------------------------------------------------------------
# Column detection
# ----------------------------------------------------------------------------
def detect_date_column(df: pd.DataFrame) -> str:
    """Pick the column that parses most reliably as a date."""
    best, best_score = None, 0.0
    for col in df.columns:
        s = df[col]
        if s.dtype.kind in "if":  # numeric -> almost certainly not a date column
            continue
        parsed = pd.to_datetime(s, errors="coerce")
        score = parsed.notna().mean()
        # prefer wide spread of unique days (a real date axis), not a constant
        if score > 0.9 and parsed.nunique() > 1:
            score += 0.001 * min(parsed.nunique(), 1000)
        if score > best_score:
            best, best_score = col, score
    if best is None:
        raise ValueError("No date-like column detected")
    return best


def detect_id_column(df: pd.DataFrame, date_col: str) -> str:
    """
    The SKU id is the non-date column whose value set partitions the table into
    roughly equal-length, date-unique panels. Score = panel regularity.
    """
    best, best_score = None, -1.0
    n = len(df)
    for col in df.columns:
        if col == date_col:
            continue
        s = df[col]
        if s.dtype.kind in "if":
            continue
        k = s.nunique(dropna=True)
        if k < 2 or k > n / 2:
            continue
        g = df.groupby(col)[date_col]
        # a true entity key has (almost) no duplicate dates inside a group
        dup_rate = 1.0 - (g.nunique().sum() / n)
        # and it should be the finest such key
        score = (1.0 - dup_rate) * (k / n)
        if score > best_score:
            best, best_score = col, score
    if best is None:
        raise ValueError("No SKU-like identifier column detected")
    return best


def classify_numeric_roles(df: pd.DataFrame, num_cols: list[str]) -> dict:
    """Heuristically map numeric columns onto supply-chain roles by name + behaviour."""
    roles: dict[str, str | None] = {
        "demand": None,
        "received": None,
        "stock": None,
        "lead_time": None,
    }
    for c in num_cols:
        lc = c.lower()
        if roles["demand"] is None and ("sold" in lc or "demand" in lc or "sales" in lc):
            roles["demand"] = c
        elif roles["received"] is None and ("receiv" in lc or "inbound" in lc or "supply" in lc):
            roles["received"] = c
        elif roles["stock"] is None and ("stock" in lc or "inventory" in lc or "on_hand" in lc):
            roles["stock"] = c
        elif roles["lead_time"] is None and ("lead" in lc):
            roles["lead_time"] = c
    return roles


def md_table(rows: list[list], headers: list[str]) -> str:
    out = ["| " + " | ".join(str(h) for h in headers) + " |",
           "|" + "|".join(["---"] * len(headers)) + "|"]
    for r in rows:
        out.append("| " + " | ".join("" if v is None else str(v) for v in r) + " |")
    return "\n".join(out)


def main() -> None:
    raw = pd.read_csv(CSV)
    lines: list[str] = []
    P = lines.append

    P("# Data Profile — `project1_supply_chain_demand.csv`")
    P("")
    P("_Generated by `scripts/profile_data.py`. Every number below is computed from the "
      "actual file; nothing here is hand-written._")
    P("")

    # --- 1. schema -----------------------------------------------------------
    P("## 1. Schema and detected roles")
    P("")
    date_col = detect_date_column(raw)
    id_col = detect_id_column(raw, date_col)
    num_cols = [c for c in raw.columns if raw[c].dtype.kind in "if"]
    roles = classify_numeric_roles(raw, num_cols)

    P(md_table(
        [[c, str(raw[c].dtype), raw[c].nunique(dropna=True), int(raw[c].isna().sum()),
          repr(raw[c].dropna().iloc[0]) if raw[c].notna().any() else ""]
         for c in raw.columns],
        ["column", "dtype", "n_unique", "n_missing", "example"],
    ))
    P("")
    P(f"- **Detected date column:** `{date_col}`")
    P(f"- **Detected SKU identifier:** `{id_col}`")
    for role, col in roles.items():
        P(f"- **Detected `{role}` column:** `{col}`")
    P("")

    df = raw.copy()
    df[date_col] = pd.to_datetime(df[date_col])
    demand_col = roles["demand"]
    recv_col = roles["received"]
    stock_col = roles["stock"]
    lt_col = roles["lead_time"]
    cat_col = next(
        (c for c in df.columns
         if c not in (date_col, id_col) and df[c].dtype.kind not in "if"
         and 1 < df[c].nunique() < df[id_col].nunique()),
        None,
    )
    P(f"- **Detected category column:** `{cat_col}`")
    P("")

    # --- 2. shape ------------------------------------------------------------
    P("## 2. Size, date range, coverage")
    P("")
    P(md_table([
        ["rows", len(df)],
        ["columns", df.shape[1]],
        ["distinct SKUs", df[id_col].nunique()],
        ["min date", df[date_col].min().date()],
        ["max date", df[date_col].max().date()],
        ["calendar days spanned", (df[date_col].max() - df[date_col].min()).days + 1],
        ["distinct dates present", df[date_col].nunique()],
        ["duplicate (sku, date) pairs", int(df.duplicated([id_col, date_col]).sum())],
        ["fully duplicated rows", int(df.duplicated().sum())],
    ], ["metric", "value"]))
    P("")

    # gaps in the daily grid, per SKU
    span = df.groupby(id_col)[date_col].agg(["min", "max", "count"])
    span["expected_days"] = (span["max"] - span["min"]).dt.days + 1
    span["missing_days"] = span["expected_days"] - span["count"]
    P(f"- SKUs with gaps in their daily grid: **{int((span['missing_days'] > 0).sum())}**")
    P(f"- Total missing calendar days across all SKUs: **{int(span['missing_days'].sum())}**")
    P("")

    # --- 3. per-SKU distribution --------------------------------------------
    P("## 3. SKU history lengths (cold-start detection)")
    P("")
    span = span.sort_values("count")
    P(md_table(
        [[i, int(r["count"]), r["min"].date(), r["max"].date(),
          df.loc[df[id_col] == i, cat_col].iloc[0] if cat_col else "",
          round(float(df.loc[df[id_col] == i, demand_col].mean()), 2)]
         for i, r in span.iterrows()],
        ["sku", "days_of_history", "first_date", "last_date", "category", "mean_daily_demand"],
    ))
    P("")
    hist = span["count"]
    # data-driven cold-start cut: largest relative gap in the sorted history lengths
    srt = np.sort(hist.values)
    gaps = np.diff(srt)
    cut_idx = int(np.argmax(gaps)) if len(gaps) else 0
    cold_cut = float((srt[cut_idx] + srt[cut_idx + 1]) / 2) if len(gaps) else 0.0
    n_cold = int((hist <= cold_cut).sum())
    P(f"- History length ranges **{int(hist.min())} – {int(hist.max())} days**.")
    P(f"- Largest natural break in history length sits at **~{cold_cut:.0f} days**, "
      f"separating **{n_cold} newly launched SKU(s)** from **{len(hist) - n_cold} established SKU(s)**.")
    P(f"- Newly launched: **{', '.join(sorted(hist[hist <= cold_cut].index.astype(str)))}**")
    P("")

    # --- 4. missing / negative / zero ---------------------------------------
    P("## 4. Data quality checks")
    P("")
    qrows = []
    for c in num_cols:
        s = df[c]
        qrows.append([
            c, int(s.isna().sum()), round(100 * s.isna().mean(), 2),
            int((s < 0).sum()), int((s == 0).sum()),
            round(float(s.min()), 2), round(float(s.median()), 2), round(float(s.max()), 2),
        ])
    P(md_table(qrows, ["column", "n_missing", "pct_missing", "n_negative", "n_zero",
                       "min", "median", "max"]))
    P("")

    if demand_col:
        zero_by_sku = df.groupby(id_col)[demand_col].apply(lambda s: float((s == 0).mean()))
        P(f"- Zero-demand days overall: **{int((df[demand_col] == 0).sum())} "
          f"({100 * (df[demand_col] == 0).mean():.1f}%)**.")
        P(f"- Highest zero-demand share for a single SKU: **{zero_by_sku.max() * 100:.1f}% "
          f"({zero_by_sku.idxmax()})**; lowest **{zero_by_sku.min() * 100:.1f}% "
          f"({zero_by_sku.idxmin()})**.")
        nan_by_sku = df.groupby(id_col)[demand_col].apply(lambda s: int(s.isna().sum()))
        if nan_by_sku.sum():
            P(f"- SKUs with missing demand values: "
              f"{', '.join(f'{k} ({v})' for k, v in nan_by_sku[nan_by_sku > 0].items())}")
        P("")

    # --- 5. category / lead time --------------------------------------------
    P("## 5. Category and lead-time distribution")
    P("")
    if cat_col:
        cat = (df.groupby(cat_col)
                 .agg(skus=(id_col, "nunique"), rows=(id_col, "size"),
                      mean_daily_demand=(demand_col, "mean"),
                      mean_lead_time=(lt_col, "mean"))
                 .round(2).sort_values("skus", ascending=False))
        P(md_table([[i] + list(r.values) for i, r in cat.iterrows()],
                   [cat_col] + list(cat.columns)))
        P("")
    if lt_col:
        lt_per_sku = df.groupby(id_col)[lt_col].nunique()
        P(f"- `{lt_col}` is **constant per SKU** for {int((lt_per_sku == 1).sum())}/{len(lt_per_sku)} SKUs "
          f"→ it is a static SKU attribute, not a time series.")
        ltv = df.groupby(id_col)[lt_col].first()
        P(f"- Lead time across SKUs: min **{int(ltv.min())}**, median **{ltv.median():.0f}**, "
          f"max **{int(ltv.max())}** days.")
        P("")
        P(md_table([[int(k), int(v)] for k, v in ltv.value_counts().sort_index().items()],
                   ["lead_time_days", "n_skus"]))
        P("")

    # --- 6. inventory consistency -------------------------------------------
    P("## 6. Inventory balance consistency")
    P("")
    P("Expected identity: `closing_stock[t] = closing_stock[t-1] + units_received[t] - units_sold[t]`.")
    P("")
    d = df.sort_values([id_col, date_col]).copy()
    d["prev_stock"] = d.groupby(id_col)[stock_col].shift(1)
    d["expected"] = d["prev_stock"] + d[recv_col] - d[demand_col]
    d["resid"] = d[stock_col] - d["expected"]
    chk = d.dropna(subset=["resid"])
    exact = float((chk["resid"].abs() < 1e-6).mean())
    within1 = float((chk["resid"].abs() <= 1.0).mean())
    P(md_table([
        ["rows checked (excl. each SKU's first day)", len(chk)],
        ["exact balance match", f"{exact * 100:.2f}%"],
        ["within ±1 unit", f"{within1 * 100:.2f}%"],
        ["mean residual", round(float(chk['resid'].mean()), 3)],
        ["median |residual|", round(float(chk['resid'].abs().median()), 3)],
        ["max |residual|", round(float(chk['resid'].abs().max()), 3)],
    ], ["check", "value"]))
    P("")
    bad = chk.loc[chk["resid"].abs() > 1.0]
    if len(bad):
        by_sku = bad.groupby(id_col).size().sort_values(ascending=False)
        P(f"- **{len(bad)} rows ({100 * len(bad) / len(chk):.1f}%)** break the balance by more than 1 unit, "
          f"spread over {by_sku.size} SKU(s).")
        P("")
        P(md_table([[i, int(v)] for i, v in by_sku.head(10).items()], ["sku", "n_violations"]))
        P("")
    P(f"- Days where stock would go negative under the identity: "
      f"**{int((chk['expected'] < 0).sum())}**; days where recorded stock is 0: "
      f"**{int((df[stock_col] == 0).sum())}**.")
    P("")

    # --- 7. demand behaviour -------------------------------------------------
    P("## 7. Demand behaviour per SKU")
    P("")
    g = df.groupby(id_col)[demand_col]
    beh = pd.DataFrame({
        "mean": g.mean(), "std": g.std(), "min": g.min(), "max": g.max(),
    })
    beh["cv"] = beh["std"] / beh["mean"].replace(0, np.nan)
    beh = beh.round(2).sort_values("cv", ascending=False)
    P(md_table([[i] + list(r.values) for i, r in beh.iterrows()],
               ["sku", "mean", "std", "min", "max", "cv (std/mean)"]))
    P("")
    P(f"- Coefficient of variation ranges **{beh['cv'].min():.2f} – {beh['cv'].max():.2f}** "
      f"(median {beh['cv'].median():.2f}). High CV SKUs need a larger safety buffer.")
    P("")

    # day-of-week signal
    dow = df.assign(dow=df[date_col].dt.dayofweek)
    dow_mean = dow.groupby("dow")[demand_col].mean()
    overall = df[demand_col].mean()
    P("### Day-of-week effect (all SKUs pooled, index vs. overall mean = 100)")
    P("")
    names = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    P(md_table([[names[int(k)], round(float(v), 2), round(100 * float(v) / overall, 1)]
                for k, v in dow_mean.items()],
               ["day", "mean_demand", "index"]))
    P("")
    spread = float(dow_mean.max() / dow_mean.min())
    P(f"- Max/min day-of-week ratio = **{spread:.3f}**. "
      f"{'A weekly pattern is present and worth modelling.' if spread > 1.10 else 'No material weekly seasonality — day-of-week features are unlikely to help.'}")
    P("")

    # trend over the panel (monthly)
    mo = df.assign(m=df[date_col].dt.to_period("M")).groupby("m")[demand_col].mean().round(2)
    P("### Monthly mean demand (pooled)")
    P("")
    P(md_table([[str(k), float(v)] for k, v in mo.items()], ["month", "mean_daily_demand"]))
    P("")

    # --- 8. machine-readable summary ----------------------------------------
    meta = {
        "date_col": date_col, "id_col": id_col, "category_col": cat_col,
        "demand_col": demand_col, "received_col": recv_col,
        "stock_col": stock_col, "lead_time_col": lt_col,
        "n_rows": int(len(df)), "n_skus": int(df[id_col].nunique()),
        "min_date": str(df[date_col].min().date()), "max_date": str(df[date_col].max().date()),
        "cold_start_cut_days": cold_cut,
        "cold_start_skus": sorted(hist[hist <= cold_cut].index.astype(str).tolist()),
        "dow_ratio": spread,
        "balance_exact_pct": exact * 100,
    }
    (ROOT / "backend" / "reports" / "data_profile.json").write_text(json.dumps(meta, indent=2))

    P("## 8. Implications for modelling")
    P("")
    P("_(see `backend/reports/model_summary.md` for how these were acted on)_")
    P("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps(meta, indent=2))
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    sys.exit(main())
